### ISSUE TITLE
Movement Direction & Speed

### ISSUE THREAD

**Issue by Heinrix** [missmealey/LifeForce#1]
Movement is locked to 8 axis (vertical, horizontal and diagonal)
This may also be the cause of diagonal speed being quicker than vertical or horizontal.

**Comment by missmealey** [comment]
Synch to latest version to see if this is more what you were thinking.

I has more of a reliance on the joystick for speed (though i cant fully test from the office) and movement should be possible along any angle.

there does still seem to be a more speed on a diagonal angle problem though. but i think i know why.

**Comment by Heinrix** [comment]
This seems to be working fine now, you can mark it as closed :)
